zachandthefriedmen/GraceShopper

.eslintrc.json, .github/CONTRIBUTING.md
Test pull request with contribution guidelines
Updated .eslintrc.json to enforce semicolons
=> docs: define contribution guide and update eslintrc

package-lock.json, script/seed.js, server/db/db.js, server/db/models/category.js, server/db/models/index.js, server/db/models/order.js, server/db/models/product.js, server/db/models/review.js, server/db/models/user.js
Defined models for users, products, reviews, categories and orders. Also defined associations between these models, and created seed file that creates two dummy instances of each model.
=> Database models

server/api/product.js
eagerly load categories when getting single product
=> Landing page #11

script/seed.js
Update seed file to include sessionIds on orders
=> fix: update seed file to include dummy sessions on orders

script/seed.js
=> fix: update console logs in seed file

client/components/main.js
---
We were about to create an entirely new navbar component when we realized there was a very functional one already created. So we added some links - to all products and to cart which should be visible on all pages, and then another link to the user's account page which is only visible once a user logs in.
=> chore: create navbar component

client/components/LandingPage.js, client/components/index.js, client/routes.js
---
We created a fairly basic landing page and set it as the default ('/') view. The landing page will be the first thing a user sees when going to Bentosbazaar.com.
=> chore: create landing page

client/components/ProductCell.js, client/components/SingleProduct.js
---
Added bootstrap classes to SingleProduct component and added items to review dummy data to test classes in order to make progress towards fulfilling issue 'View-Single-Product-#8'.
=> View-single-product-#8 (Added CSS)

client/components/Footer.js, client/components/main.js
… logo
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, the reasoning behind the current solution, and any other relevant information for posterity.
---
Added a footer to the page in order to work towards fulfilling issue 'Footer-#28'
Footer contains logo with a link to '/', and everyone's names
Added a link to '/' on the navbar title and footer to main to display component
=> Footer-#28

client/store/category.js, client/store/category.spec.js, client/store/index.spec.js, client/store/order.js, client/store/order.spec.js, client/store/product.js, client/store/product.spec.js, client/store/review.js, client/store/review.spec.js, client/store/reviews.js, client/store/user.spec.js, server/api/review.js
---
main functionality for reducers added, updated relevant backend route, and wrote tests for all reducers
=> Connect database #4

client/store/index.js
---
fixed up the combine reducers
=> fix: update reducers index to combine reducers from all modules

package-lock.json, package.json, server/api/order.js, server/db/models/order.js, server/index.js
Updated order model and added functionality to create new order (cart) with every new session
=> Quick fixes

server/index.js
Removed completely unnecessary console.log
=> fix: remove unnecessary console log

server/api/category.js
added eager loading to all categories api route
=> fix: add eager loading to all categories

client/components/Cart.js, client/components/CartCell.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, the reasoning behind the current solution, and any other relevant information for posterity.
---
Added basic bootstrap CSS to cart in order to help fulfill issue "View-cart-#9"
=> View cart #9

package.json
Updated node version in package.json to address heroku deployment issues
=> fix: update node version in package.json

server/api/cart.js, server/api/index.js, server/db/models/order.js
- add api/cart routes
- fix order database model email field
=> chore: add api route for carts, fix order model

client/components/auth-form.js, client/store/user.js, server/auth/index.js
Fix auth form so that it aligns with our database model for users and works with login and signup
=> chore: fix auth form to work with login and signup

client/components/AccountView.js, client/components/LandingPage.js
- change accountview password fields to password type
- replace landing page image
=> fix: replace landing page image and fix accountview password fields

script/seed.js
=> added more data

client/components/AccountView.js, client/components/OrderCell.js
took out dummy reviews, reformatted orderCell, reformatted (slightly) account page by fixing integrations
=> fix: format order history, intelligently display integrations

client/components/AccountView.js, client/components/AdminPage.js, client/components/AdminProductForm.js, client/components/Footer.js, client/components/LandingPage.js, client/components/Order.js, client/store/cart.js, server/api/order.js
- clean up commented artifact code
- remove leftover console.logs
=> fix: clean up commented blocks and console.logs

server/api/order.js
- move res.sendStatus into try block
=> fix: fix api order delete route
